package com.optimiza.ehope.lis.helper;

public enum ContainerImage {

	URINE_24_HOUR("URINE_24_HOUR"),
	ANAEROBIC_ADULT_BLOOD_CULTURE_BOTTLE("ANAEROBIC_ADULT_BLOOD_CULTURE_BOTTLE"),
	ANAEROBIC_PEDIATRIC_BLOOD_CULTURE_BOTTLE("ANAEROBIC_PEDIATRIC_BLOOD_CULTURE_BOTTLE"),
	ARTBOARD_1("ARTBOARD_1"),
	ARTBOARD_5("ARTBOARD_5"),
	ARTBOARD_10("ARTBOARD_10"),
	ARTBOARD_12("ARTBOARD_12"),
	CAPILLARY_TUBE("CAPILLARY_TUBE"),
	GLASS_SLIDE("GLASS_SLIDE"),
	NEONATAL_CARD("NEONATAL_CARD"),
	PLAIN_TUBE_BODY_FLUID("PLAIN_TUBE_BODY_FLUID"),
	STOOL("STOOL"),
	SWAB_WITH_GEL_TRANSPORT_MEDIA("SWAB_WITH_GEL_TRANSPORT_MEDIA"),
	SWAB_WITHOUT_TRANSPORT_MEDIA("SWAB_WITHOUT_TRANSPORT_MEDIA");

	private String value;

	private ContainerImage(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

}
